config/routes.rb
Rails.application.routes.draw do
  
get '/home', to: 'customers#home', as: "home"
  resources :orders
  resources :menu_items
  resources :customers

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	has_many :menu_items, through: :orders
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
	has_many :orders
	has_many :customers, through: :orders

	def money_format
		number_to_currency(self.price, :unit => "$")
	end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :menu_item

  def date_format
    I18n.l(self.created_at.in_time_zone("Eastern Time (US & Canada)"), format: :long)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	before_action :find_customer, only: [:show, :edit, :update, :destroy]

	def home

	end

	def index
		@customers = Customer.all
	end

	def show

	end


	def new
		@customer = Customer.new
	end

	def create
		customer = Customer.create(customer_strong_params)

		redirect_to customer_path(customer)
	end

	def edit

	end

	def update
		@customer.update(customer_strong_params)

		redirect_to customer_path(@customer)
	end

	def destroy
		@customer.destroy

		redirect_to customers_path
	end

	private

	def customer_strong_params
		params.require(:customer).permit(:name, :gender)
	end

	def find_customer
		@customer = Customer.find(params[:id])
	end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

	before_action :find_menu_item, only: [:show, :edit, :update, :destroy]

	def index
		@menu_items = MenuItem.all
	end

	def show

	end

	def new
		@menu_item = MenuItem.new	
	end

	def create
		menu_item = MenuItem.create(menu_item_strong_params)

		redirect_to menu_item_path(menu_item)
	end

	def edit

	end

	def update
		menu_item = @menu_item.update(menu_item_strong_params)

		redirect_to menu_item_path(@menu_item)
	end

	def destroy
		@menu_item.destroy

		redirect_to menu_items_path
	end

	private

	def find_menu_item
		@menu_item = MenuItem.find(params[:id])
	end

	def menu_item_strong_params
		params.require(:menu_item).permit(:name, :price)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    before_action :find_order, only: [:show, :edit, :update, :destroy]

    def new
        @order = Order.new
    end

    def show
    end

    def create
        order = Order.create(order_strong_params)
        redirect_to order_path(order)
    end
    
    def edit
    end

    def update
        @order.update(order_strong_params)
        redirect_to order_path(@order)
    end

    def destroy
        @order.destroy
        redirect_to orders_path
    end

    private

    def find_order
        @order = Order.find(params[:id])
    end

    def order_strong_params
        params.require(:order).permit(:customer_id, :menu_item_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_customer_form.html.erb
<%= form_for @customer do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :gender %>
	<%= f.select :gender, options_for_select(['Male',"Female"], selected: @customer.gender) %>

	<%= f.submit submit_text %>

<% end %>

app/views/customers/edit.html.erb
<h1>Update Customer</h1>

<%= render partial:"customer_form", locals:{submit_text: "Update Customer"} %>

<p><%= link_to "Home", home_path %></p>

app/views/customers/home.html.erb
<h1>Welcome to your Restaurant</h1>

<h3><%= link_to "View the Menu", menu_items_path %></h3>

<h3><%= link_to "View Customers", customers_path %></h3>

<h3><%= link_to "Create an Order", new_order_path %></h3>

app/views/customers/index.html.erb
<h1>Customers</h1>


	<% @customers.each do |customer| %>
		<div><%= link_to customer.name, customer_path(customer) %></div>
	<%end%>
<br>

<div><%= button_to "New", new_customer_path, method: "get" %></div>

<p><%= link_to "Home", home_path %></p>

app/views/customers/new.html.erb
<h1>Create New Customer</h1>

<%= render partial:"customer_form", locals: {submit_text: "Create Customer"} %>

<p><%= link_to "Home", home_path %></p>

app/views/customers/show.html.erb
<h1> <%= @customer.name %> </h1>

<h4> Gender: <%= @customer.gender %></h4>

<%= button_to "Create New Order", new_order_path, method: 'get' %> 

<h3> Orders: </h3>

    <% @customer.orders.each do |order| %>
    <div><%= link_to order.date_format, order_path(order) %></div>
    <% end %>
<br>

<%= button_to "Edit", edit_customer_path, method: 'get' %>
<%= button_to "Delete", @customer , method: :delete %>
<br>
<%= button_to "View All Customers", customers_path, method: "get" %>

<p><%= link_to "Home", home_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_menu_item_form.html.erb
<%= form_for @menu_item do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :price %>
	<%= f.number_field :price, value: number_with_precision(f.object.price, precision: 2),step: 0.01%>

	<%= f.submit submit_text %>
<% end %>

app/views/menu_items/edit.html.erb
<h1> Update <%=@menu_item.name%></h1>

<%= render partial:"menu_item_form", locals:{submit_text:"Update Item"} %>

<p><%= link_to "Home", home_path %></p>

app/views/menu_items/index.html.erb
<h1>Menu Items</h1>


<%@menu_items.each do |m| %>
	<div><%= link_to m.name, menu_item_path(m) %>
<% end %>


<br>
<br>

<%= button_to "Create new item", new_menu_item_path, method: "get" %>

<p><%= link_to "Home", home_path %></p>

app/views/menu_items/new.html.erb
<h1>Create New Menu Item</h1>

<%= render partial:"menu_item_form", locals:{submit_text: "Create New Item"} %>

<p><%= link_to "Home", home_path %></p>

app/views/menu_items/show.html.erb
<h1><%= @menu_item.name %></h1>

<h2>Price: <%=number_to_currency(@menu_item.price, unit: "$") %></h2>

<%= button_to "Edit", edit_menu_item_path, method:"get" %><%= button_to "Delete", @menu_item, method: :delete %>

<%= button_to "Order Item", new_order_path, method:"get" %>

<%= button_to "View all Menu Items", menu_items_path, method: "get" %>

<p><%= link_to "Home", home_path %></p>

app/views/orders/_order_form.html.erb
<%= form_for @order do |f| %>
<%= f.label :customer %>
<%= f.collection_select(:customer_id, Customer.all, :id, :name) %><br><br>
<%= f.label :menu_item %>
<%= f.collection_select(:menu_item_id, MenuItem.all, :id, :name) %><br><br><br>
<%= f.submit submit_text %>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render partial: "order_form", locals: {submit_text:"Update Order"}%>

<p><%= link_to "Home", home_path %></p>

app/views/orders/new.html.erb
<h1>Create Order</h1>

<%= render partial: "order_form", locals: {submit_text: "Submit order"} %>
<br>
<br>
<div>Don't see your name?</div>
<%= button_to "Add Customer", new_customer_path, method: "get" %>

<p><%= link_to "Home", home_path %></p>

app/views/orders/show.html.erb
<h1><%= @order.date_format %></h1>


<h2>Customer's Name: <%= link_to @order.customer.name, customer_path(@order.customer) %></h2>
<h2>Menu Item's Name: <%= link_to @order.menu_item.name, menu_item_path(@order.menu_item) %></h2>
<h2>Order Total: <%= number_to_currency(@order.menu_item.price, unit: "$") %></h2>
<%= button_to "Edit Order", edit_order_path, method: 'get' %> 


<p><%= link_to "Home", home_path %></p>